export const forYouTabBarIcon = require('../assets/icons/newspaper.png');
export const international = require('../assets/icons/international.png');
export const entertainment = require('../assets/icons/entertainment.png');
export const night = require('../assets/icons/night.png');
export const headphone = require('../assets/icons/headphones.png');
export const journalist = require('../assets/icons/journalist.png');
export const search = require('../assets/icons/search.png');
export const rising = require('../assets/icons/rising.png');
export const profile = require('../assets/icons/profile-icon.jpeg');
export const notification = require('../assets/icons/notification-icon.png');
export const saved = require('../assets/icons/saved-icon.png');
export const dataSaver = require('../assets/icons/saved-icon.png');
export const darkMode = require('../assets/icons/dark-mode-icon.png');
// export const personalize = require('../assets/icons/per')
export const policies = require('../assets/icons/polices-icon.png');
// export const signout =require('../assets/icons/s')
// export const tiger = require('../assets/images/Rectangle 3.png');
